CREATE DATABASE IF NOT EXISTS user_db;
CREATE DATABASE IF NOT EXISTS hub_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS product_db;
CREATE DATABASE IF NOT EXISTS vendor_db;
CREATE DATABASE IF NOT EXISTS delivery_db;