spring:
  application:
    name: hub
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

    data:
      redis:
        host: localhost
        port: 6379
        username: default
        password: ${REDIS_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          default_schema: hub_service

  service:
    jwt:
      access-expiration: ${JWT_ACCESS_EXPIRATION}
      secret-key: ${JWT_SECRET_KEY}

server:
  port: 18082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/