spring:
  application:
    name: hub-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/8logistics
    username: sunghun
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true      # 쿼리 정렬 설정
        use_sql_comments: true

  service:
    jwt:
      access-expiration: 3600000
      secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1

server:
  port: 18082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
#    path: /api/hub/v3/api-docs
    # 게이트웨이 라우팅에서 prefix를 제거하지 않았다면 해당 설정을 추가
  enable-spring-security: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
