server:
  port: 18083

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://msa-db:3306/product_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: product_service

  service:
    jwt:
      access-expiration: 3600000
      refresh-expiration: 4000000
      secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1

eureka:
  client:
    service-url:
      defaultZone: http://server:19090/eureka/