server:
  port: 19091

spring:
  main:
    web-application-type: reactive  # Spring 애플리케이션이 리액티브 웹 애플리케이션으로 설정됨
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vendor-service-doc
          uri: lb://vendor-service
          predicates:
            - Path=/api/v1/vendors/v3/api-docs
          filters:
            - RewritePath=/api/v1/vendors/v3/api-docs, /v3/api-docs
        - id: vendor-service
          uri: lb://vendor-service
          predicates:
            - Path=/api/v1/vendors/**
        - id: product-service-doc
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/v3/api-docs
          filters:
            - RewritePath=/api/v1/products/v3/api-docs, /v3/api-docs
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: order-service-doc
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/v3/api-docs
          filters:
            - RewritePath=/api/v1/orders/v3/api-docs, /v3/api-docs
        - id: order-service  # 라우트 식별자
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**, /api/v1/noties/**
        - id: hub-service-doc
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/v3/api-docs
          filters:
            - RewritePath=/api/v1/hubs/v3/api-docs, /v3/api-docs
        - id: hub-service  # 라우트 식별자
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**, /api/v1/hubPaths/**
        - id: delivery-service-doc
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/v3/api-docs
          filters:
            - RewritePath=/api/v1/deliveries/v3/api-docs, /v3/api-docs
        - id: delivery-service  # 라우트 식별자
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/deliveries/**, /api/v1/deliveryPaths/**
      discovery:
        locator:
          enabled: true  # 서비스 디스커버리를 통해 동적으로 라우트를 생성하도록 설정

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/  # Eureka 서버의 URL을 지정

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    com.netflix.discovery: DEBUG

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: user-service
        url: /api/v1/users/v3/api-docs
      - name: hub-service
        url: /api/v1/hubs/v3/api-docs
      - name: vendor-service
        url: /api/v1/vendors/v3/api-docs
      - name: product-service
        url: /api/v1/products/v3/api-docs
      - name: order-service
        url: /api/v1/orders/v3/api-docs
      - name: delivery-service
        url: /api/v1/deliveries/v3/api-docs