spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:mysql://msa-db:3306/delivery_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true

server:
  port: 18085

service:
  jwt:
    access-expiration: 3600000
    refresh-expiration: 4000000
    secret-key: 401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1

eureka:
  client:
    service-url:
      defaultZone: http://server:19090/eureka/


management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0